apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sqlsrv
  name: sqlsrv
spec:
  containers:
  - image: nginx
    name: sqlsrv
    envFrom:
    - configMapRef:
        name: db-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
